
export const metadata = {
  title: 'Andrei Next js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="childrenContainer">
        {children}
        </div>
  )
}
