import CustomCursor from "./components/cursor"
import Footer from "./Footer/page"
import './global.css'
import { Metadata } from "next"
import ProgressBar from "./components/ProgressBar/ProgressBar"
import { Analytics } from "@vercel/analytics/next"

export const viewport = {
  width: "device-width",
  initialScale: 0.1,
  maximumScale: 1,
  userScalable: true,
};


export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Andrei Website",
   
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Analytics/>
        <ProgressBar />
        <CustomCursor/>
        <div>
        {children}
        </div>
          <Footer></Footer>
        
        </body>
    </html>
  )
}
