import CustomCursor from "./components/cursor"
import Footer from "./Footer/page"
import Header from "./Header/page"
import './global.css'
import { Metadata } from "next"


export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Andrei Website",
    template: "%s | Andrei Website",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CustomCursor/>
        <Header></Header>
        <div className="childrenContainer">
        {children}
        </div>
          <Footer></Footer>
        
        </body>
    </html>
  )
}
