import Header from "../Header/page"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Andrei Website",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <>
       <Header></Header>
        {children}
   </>
  )
}
