//import Footer from "../Footer/page"
//import Header from "../Header/page"


export const metadata = {
  title: 'Andrei Next js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <head>
      <style>
       
      </style>
     </head>
      <body>
        {children}
        </body>
    </html>
  )
}
